env: "production"
tokenKey: "secretkey"
postgres:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  database: "textvault"
s3:
  bucket: "textvault"
redis:
  host: "localhost"
  port: "6379"
  password: "test-password"
  db: 0